INSERT INTO amenity (amenity) VALUES ('dog friendly');
INSERT INTO amenity (amenity) VALUES ('cat friendly');
INSERT INTO amenity (amenity) VALUES ('turtle friendly');
INSERT INTO amenity (amenity) VALUES ('restrooms');
INSERT INTO amenity (amenity) VALUES ('fenced area');
INSERT INTO amenity (amenity) VALUES ('hot dog stand');
INSERT INTO amenity (amenity) VALUES ('parking area');
INSERT INTO amenity (amenity) VALUES ('lake');
INSERT INTO amenity (amenity) VALUES ('wifi');
INSERT INTO amenity (amenity) VALUES ('playground for kids');
INSERT INTO amenity (amenity) VALUES ('basketball area');
INSERT INTO amenity (amenity) VALUES ('soccer area');